POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdzEiLCJpZCI6MywiaWF0IjoxNjk2MzI3NTAxfQ.FrTmj5zzmSOooTXWdGkDRpBlyzrKZW3G2Yoz6Jxsm7c

{
    "content": "note 2",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "tejfellow1",
    "name": "TEJ Fellow 1"
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "tejfellow4",
    "password": "secret"
}
###
PUT http://localhost:3001/api/users/tejfellow4
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlamZlbGxvdzQiLCJpZCI6MSwiaWF0IjoxNjk2MzI5Nzg3fQ.ZusOITGWWcvJEQ_I5IegB05RjXu4n7C_L72uUpx8a1s

{
    "disabled": false
}