DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/1
###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "sample by liza",
    "important": false,
    "userId": "64ddd9b4aade6eceab05c041"
}
###
PUT http://localhost:3001/api/notes/64dabd8706d2a6f28dd50f3f
content-type: application/json 

{
    "content": "sam",
    "important": true
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "user":"apple",
    "username":"apple M2",
    "password":"password123"
}